remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

---
![Alt text](/assets/images/QCL.png) 
title: Intro to GIT workflow
author: Daniel Perez
description: Introductory course to GIT workflow using graphical user interface.
---
